17:38:51,528 (main) WARN  [DataNucleus.Datastore.Schema] - You have specified the default schema as applicationidentity8 but for this datastore this has been changed to APPLICATIONIDENTITY8. This is likely due to missing quote characters, or the datastore storing things in a different case
17:38:52,808 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,235 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,359 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,480 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,620 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,689 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,736 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,799 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,936 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:53,993 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,097 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,151 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,233 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,300 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,407 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,498 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,570 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

17:38:54,639 (main) WARN  [DataNucleus.Persistence] - Execution of method "remove" on field "entries" caused an error : Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
org.datanucleus.exceptions.NucleusDataStoreException: Could not update the foreign key using statement : UPDATE APPLICATIONIDENTITY8.CART_ENTRIES SET CART_ID=? WHERE ID=?
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:335)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	... 29 more
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more
Nested Throwables StackTrace:
java.sql.SQLIntegrityConstraintViolationException: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.updateElementFk(FKSetStore.java:320)
	at org.datanucleus.store.rdbms.scostore.FKSetStore.remove(FKSetStore.java:699)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:691)
	at org.datanucleus.store.types.wrappers.backed.HashSet.remove(HashSet.java:651)
	at org.datanucleus.store.rdbms.mapping.java.PersistableMapping.preDelete(PersistableMapping.java:1177)
	at org.datanucleus.store.rdbms.request.DeleteRequest.execute(DeleteRequest.java:208)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObjectFromTable(RDBMSPersistenceHandler.java:494)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.deleteObject(RDBMSPersistenceHandler.java:466)
	at org.datanucleus.state.StateManagerImpl.internalDeletePersistent(StateManagerImpl.java:1207)
	at org.datanucleus.state.StateManagerImpl.deletePersistent(StateManagerImpl.java:5464)
	at org.datanucleus.ExecutionContextImpl.deleteObjectInternal(ExecutionContextImpl.java:2336)
	at org.datanucleus.ExecutionContextImpl.deleteObjectWork(ExecutionContextImpl.java:2258)
	at org.datanucleus.ExecutionContextImpl.deleteObjects(ExecutionContextImpl.java:2150)
	at org.datanucleus.api.jdo.JDOPersistenceManager.deletePersistentAll(JDOPersistenceManager.java:832)
	at org.apache.jdo.tck.JDO_Test.deleteTearDownClasses(JDO_Test.java:472)
	at org.apache.jdo.tck.JDO_Test.localTearDown(JDO_Test.java:394)
	at org.apache.jdo.tck.JDO_Test.tearDown(JDO_Test.java:361)
	at org.apache.jdo.tck.JDO_Test.runBare(JDO_Test.java:292)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.textui.TestRunner.doRun(TestRunner.java:116)
	at org.apache.jdo.tck.util.BatchTestRunner.doRun(BatchTestRunner.java:124)
	at org.apache.jdo.tck.util.BatchTestRunner.start(BatchTestRunner.java:169)
	at org.apache.jdo.tck.util.BatchTestRunner.main(BatchTestRunner.java:140)
Caused by: ERROR 23502: Column 'CART_ID'  cannot accept a NULL value.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeColumn(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.normalizeRow(Unknown Source)
	at org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(Unknown Source)
	at org.apache.derby.impl.sql.execute.UpdateResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 38 more

